// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meosameglgowwuhdupln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lb3NhbWVnbGdvd3d1aGR1cGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0OTUzNDksImV4cCI6MjA1NTA3MTM0OX0.UyJZdptg2lWQQQJ-fdCy8T_H2ENCPODwXKgXtfVtyOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);